pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30

production:
  <<: *pg
  port: 5432
  database: impact_tracker_v3
  host: localhost
  username: developer
  password: developer

# production:
#   <<: *pg
#   port: <%= ENV["DB_PORT"] %>
#   database: <%= ENV["DB_NAME"] %>
#   host: <%= ENV["DB_HOST"] %>
#   username: <%= ENV["DB_USERNAME"] %>
#   password: <%= ENV["DB_PASSWORD"] %>